=== cyril-ld/converter/src/main/java/org/data/UnitesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT grandeurs (grandeur+)>

<!ELEMENT grandeur (unites+)>
<!ATTLIST grandeur nom ID #REQUIRED>

<!ELEMENT unites (unite)+>

<!ELEMENT unite EMPTY>
<!ATTLIST unite
    nom ID #REQUIRED
    symbole CDATA #REQUIRED
    etalon CDATA #IMPLIED
    ratio CDATA #REQUIRED>

=== cyril-ld/converter/src/main/java/org/data/format_stockage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE grandeurs SYSTEM "unitesDTD.dtd">
<grandeurs>
    <grandeur nom="LONGUEUR">
        <unites>
            <unite nom="mètre" symbole="m" etalon="true" ratio="1"/>
            <unite nom="millimètre" symbole="mm" ratio="0.001"/>
            <unite nom="centimètre" symbole="cm" ratio="0.01"/>
            <unite nom="decimètre" symbole="dm" ratio="0.1"/>
            <unite nom="décamètre" symbole="dam" ratio="10"/>
            <unite nom="hectomètre" symbole="hm" ratio="100"/>
            <unite nom="kilomètre" symbole="km" ratio="1000"/>
            <unite nom="yard" symbole="yd" ratio="0.9144"/>
            <unite nom="pouce" symbole="po" ratio="39.37"/>
            <unite nom="pied" symbole="ft" ratio="3.281"/>
            <unite nom="mille_marin" symbole="M" ratio="0.0005399568"/>
            <unite nom="mile_terrestre" symbole="mi" ratio="0.000621504"/>
            <unite nom="année_lumière" symbole="al" ratio="0.0000000000000000105697"/>
        </unites>
    </grandeur>
    <grandeur nom="TEMPS">
        <unites>
            <unite nom="seconde" symbole="s" ratio="1"/>
        </unites>
    </grandeur>
</grandeurs>
